name: Test

on:
  push:
    branches:
      - "main"

jobs:

  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./
        with:
          version: ${{ github.ref_name }}
          docs-dir: 'docs'
          github-token: ${{ secrets.GITHUB_TOKEN }}
