name: Test

on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: ${{ github.repository_id }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./
        with:
          version: latest
          docs-dir: 'docs'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          force-orphan: true
          publish-branch: ${{ github.ref_name == github.event.repository.default_branch && 'gh-pages' || 'publish-test-ci' }}
